### ISSUE TITLE
[Feature request] Possibility to configure window size

### ISSUE THREAD

**Issue by hamiller** [diegodario88/quake-terminal#1]
Thanks for this good extension!

Maybe you could add the possibility to configure the used window size, so terminal will not use the whole screen:
this could be a configurable percentage or instead a toggle with maybe like the upper 50% of the screen (like in quake...)

**Comment by diegodario88** [comment]
Thank you for your suggestions! It's great to hear that you found the extension useful. 

I'm pleased to inform you that I've already implemented this feature in this  [commit](https://github.com/diegodario88/quake-terminal/commit/01d4c2b9ac9d9ac66afa0321b31d5eddcf6d2253) 🫡

Any feedbacks are welcome

**Comment by hamiller** [comment]
Awesome :+1:
