### ISSUE TITLE
Unable to use backtick (`) as a shortcut

### ISSUE THREAD

**Issue by woodsb02** [diegodario88/quake-terminal#12]
I am unable to use a single backtick (`) key (also known as grave) as a shortcut.
This is my preferred key binding, and I can't help the muscle memory that comes with it.

When I want to insert a backtick elsewhere, and can't type it because it just drops down a terminal instead, I simply copy the character from elsewhere.

**Comment by woodsb02** [comment]
I don't think it's necessary to prevent the user making this decision - I say let them choose.

In particular, the backtick key is the one used in the original quake game to display the console - so suggest it's a suitable choice.

I was able to use the dconf editor to manually set the key binding, by setting `org.gnome.shell.extensions.quake-terminal.terminal-shortcut` to `['grave']`.

**Comment by diegodario88** [comment]
> I don't think it's necessary to prevent the user making this decision - I say let them choose.
>
That's a solid point.

> In particular, the backtick key is the one used in the original quake game to display the console - so suggest it's a suitable choice.
> 
I will give it a try as soon as I have time.

> I was able to use the dconf editor to manually set the key binding, by setting `org.gnome.shell.extensions.quake-terminal.terminal-shortcut` to `['grave']`.
>
That's why  I love linux people 😄

**Comment by diegodario88** [comment]
Hi there, @woodsb02 !

Could you do us a favor and give the version on the main branch a try to see if it resolves your issue?

Your feedback would be much appreciated! Thanks!

**Comment by freimair** [comment]
I use ['Menu'] via dconf. On my machines running Arch Linux, 'Menu' is the Caps-Lock-Key. I almost never use Caps-Lock as intended and the key is conveniently places to be easily reachable.

That being said, I too say let people choose.

**Comment by fredszaq** [comment]
Hi there ! I just setup quake terminal on another laptopthat is using a french iso layout keyboard, in that case the obvious choice to toogle the terminal is the ² key (the one that was used for the terminal in quake) The ui didn't let me set that binding but I managed to apply the same trick as @woodsb02 by setting `org.gnome.shell.extensions.quake-terminal.terminal-shortcut` to `['twosuperior']` in dconfeditor

**Comment by diegodario88** [comment]
Hi there, @fredszaq! I've just made some updates to the main branch, and I'm really hopeful that they've resolved the issue. Would you mind giving it a try, please? 😊

**Comment by fredszaq** [comment]
Working as expected on my side ! thanks !

**Comment by woodsb02** [comment]
> Hi there, @woodsb02 !
> 
> Could you do us a favor and give the version on the main branch a try to see if it resolves your issue?
> 
> Your feedback would be much appreciated! Thanks!

Yep, the main branch now let's me select any key I want, including the backtick key - thanks very much. 👍

**Comment by wrobelda** [comment]
For the record, I have a similar problem, except trying to set Meta + ` key as a shortcut and it doesn't work. I suppose Meta is the problem here, but don't see why it should be?
