### ISSUE TITLE
Configurable Window features 'Always on top' and 'Exclude from Overview'

### ISSUE THREAD

**Issue by Henry78** [diegodario88/quake-terminal#14]
Add an options to the settings menu and make this window properties configurable:
- 'Always on top'
- 'Exclude from Overview/Taskbar'

Use case: My desired workflow is to bring up the terminal using the hotkey when needed, switch between different application with alt-tab and then hide the terminal with the hotkey again.

Stretch goal: Have the terminal in the overwiew and accessible by alt-tab only while it's visible.

**Comment by diegodario88** [comment]
> Add an options to the settings menu and make this window properties configurable:
> 
>     * 'Always on top'
> 
It's already done in the main branch. ✅

>     * 'Exclude from Overview/Taskbar'
> 
> Use case: My desired workflow is to bring up the terminal using the hotkey when needed, switch between different application with alt-tab and then hide the terminal with the hotkey again.
> 
If I'm getting this right, you can achieve this by disabling auto-hide, switching between different windows applications with Alt-Tab, and simply using the hotkey to bring up the terminal when needed, pressing it again to hide it.

**Comment by petre2dor** [comment]
Hi @diegodario88 ,
I tried setting up the main branch (with the goal of doing some development), but I encountered an issue when trying to open the settings: `Error: GSettings key always-on-top not found in schema org.gnome.shell.extensions.quake-terminal`

![image](https://github.com/diegodario88/quake-terminal/assets/676869/b698d8e8-2e9f-4a88-a2fe-2893cc1f290b)

And a bit of a tangent, if you could document your dev setup and workflow, it would help a lot onboarding newcomers like myself. 

Anyway, thank you for sharing your work :)

**Comment by diegodario88** [comment]
Hey @petre2dor, I appreciate you bringing that issue to my attention. I've just pushed an update commit that should resolve it.

Have you given the manual installation method, as outlined in the readme, a try? This is the process I use for building and testing my changes. One thing that differs from your setup is that I'm running on Wayland, so I occasionally need to either log out and log back in or run a nested session like this:

```bash
env GNOME_SHELL_SLOWDOWN_FACTOR=2 MUTTER_DEBUG_DUMMY_MODE_SPECS=1920x1280 dbus-run-session -- gnome-shell --nested --wayland
```

Let me know if you encounter any issues or if there's anything else I can assist you with.

**Comment by petre2dor** [comment]
Thanks for the quick fix @diegodario88!
I was able to test it, but the nested session is not very usable(I cannot always start a terminal), so had to logout and log back in.

Best regards :)

**Comment by yukijoou** [comment]
commenting because i'd like to have hide from overview and hide from alt-tab too.

seems like the `quake-mode` extension had this feature, though it's not been updated to the latest gnome version unfortunately :c

[seems like that's how they got it to work](https://github.com/repsac-by/gnome-shell-extension-quake-mode/blob/50d4505d109ac474ed7b82397447559ddcebd7f8/quake-mode%40repsac-by.github.com/extension.js#L145-L183), maybe a similar feature could be implemented here :)

**Comment by diegodario88** [comment]
Hi there, @yukijoou!

Could you do us a favor and give the version on the main branch a try to see if it meets your needs?

Your feedback would be much appreciated! Thanks!

**Comment by yukijoou** [comment]
hi, thanks for the swift response! it does seem to work! at first it seemed bugged, but toggling the option on and off again made it behave as expected!

thank you so much :)

**Comment by yukijoou** [comment]
reporting back: it seems like if i kill the application running in quake-terminal and re-start it, i need to uncheck-recheck the setting for it to hide the window again - would be neat if that was done automatically

**Comment by diegodario88** [comment]
could you provide some evidence? Everything is works as expected in here

**Comment by Henry78** [comment]
Tetsted with GNOME Terminal: Works very well, had no issues.

**Comment by diegodario88** [comment]
I'm going to close this for the moment, but please don't hesitate to reopen.
