### ISSUE TITLE
Settings are not available after installation

### ISSUE THREAD

**Issue by M0Rf30** [diegodario88/quake-terminal#24]
Thanks for this fork,
I installed it on arch linux with gnome 45.1 going on extensions.gnome.org and when I click on settings this stacktrace appears:

```
TypeError: app is null

Stack trace:
  getAppIconImage@file:///home/user/.local/share/gnome-shell/extensions/quake-terminal@diegodario88.github.io/prefs.js:53:24
  fillPreferencesWindow@file:///home/user/.local/share/gnome-shell/extensions/quake-terminal@diegodario88.github.io/prefs.js:175:34
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:36:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
  ```

**Comment by petre2dor** [comment]
Hi @M0Rf30,

Do you also see in the log something like this before this error?
`Unable to locate a terminal application with the specified ID...`
Can you please paste that hole line here?

Thanks!

**Comment by petre2dor** [comment]
Looks like you don't have the Gnome default terminal app installed: `org.gnome.Terminal.desktop`

I am going to push a PR to allow this case and it will look something like this:

![image](https://github.com/diegodario88/quake-terminal/assets/676869/13fe4bf0-20c0-4970-8aa3-6e2ed5a8a656)

**Comment by petre2dor** [comment]
@M0Rf30 Please test my PR if you can #25.
You can clone [my fork](https://github.com/petre2dor/quake-terminal/tree/main) and follow the Setup instructions from Readme.

**Comment by M0Rf30** [comment]
> @M0Rf30 Please test my PR if you can #25. You can clone [my fork](https://github.com/petre2dor/quake-terminal/tree/main) and follow the Setup instructions from Readme.

Yeah it works flawlessly
