### ISSUE TITLE
Unable to use multiple windows of tilix

### ISSUE THREAD

**Issue by sannagy90** [diegodario88/quake-terminal#27]
The extensions is working as expected if there is no more than one tilix window open.
If there are new tilix windows opened, they are moved to the position to the original dropdown terminal and the behavior is unpredictable. 
[Screencast from 2023-12-04 17-26-37.webm](https://github.com/diegodario88/quake-terminal/assets/51812249/085a3cd0-77af-4a01-991e-8656313a769d)

**Comment by freimair** [comment]
that most probably is cause by quake terminal taking the last window of the configured application everytime.

I stumbled over this behavior when I did the "terminal per workspace"-feature https://github.com/diegodario88/quake-terminal/pull/9. here is the specific commit: https://github.com/diegodario88/quake-terminal/pull/9/commits/86cba2a9f3bada1b36d8456505b017b29781a8e8
