### ISSUE TITLE
Exception when disabling this extension

### ISSUE THREAD

**Issue by rotorek** [diegodario88/quake-terminal#3]
When going into Extensions and disabling this extension, I get:
`this._quakeMode is null`
message and the extension can't be re-enabled.
Replicating on SuSE Tumbleweed -- GNOME Shell 45.0
![Screenshot from 2023-10-06 08-00-54](https://github.com/diegodario88/quake-terminal/assets/26999615/52176ca6-5806-42b3-9c1f-910977193fd2)

**Comment by diegodario88** [comment]
Hey, thanks for bringing it to my attention. There's already a fix in the main branch, and concurrently, a revision is underway for the gnome-shell-extensions. We should have a version 3 available soon
