### ISSUE TITLE
Stealing other terminals

### ISSUE THREAD

**Issue by Artifechs** [diegodario88/quake-terminal#37]
This is a bit tough to reproduce, but it happens very often for me.

I usually have another terminal open in addition to the drop-down. Sometimes, this extension will think that it should manage that other terminal instead of the drop-down one, making the terminal it was supposed to manage completely hidden and unreachable.

The only fix I found is to quit all terminal sessions and restart the extension.

Perhaps the "terminal-id" is not quite unique enough?

**Comment by diegodario88** [comment]
Hey there,

The "terminal-id" parameter specifies the terminal emulator to be launched. This application can instantiate one or more windows. The intended design of this extension is to have only one window that you can summon in any workspace.

Not sure if it applies to you, but most of my workflow is inside a terminal multiplexer that handles sessions, windows, and panes within that single window.

**Comment by Artifechs** [comment]
I always use 2 separate terminals, one for coding and another for running servers/compiling/etc, which I keep handy in a "scratchpad", like what this extension offers.

If you only intended to develop this extension for your own use case and not accommodate others, then my bad, I'm barking up the wrong tree.

I've switched to Hyprland in the meantime, which satisfies this need for me.
