### ISSUE TITLE
wezterm crashes when you try to open a new tab

### ISSUE THREAD

**Issue by naddeoa** [diegodario88/quake-terminal#39]
If I pick wezterm as the Terminal Application option, use my hotkey to summon an instance, and then hit ctrl+shift+T to open a new tab then I get a crash and an error

![image](https://github.com/user-attachments/assets/a0e65119-a254-4a8c-8a65-d4646ffa6129)

It probably has something to do with the dimensions of the window or some other state changing since this also happens if you modify your wezterm config to hide/show the title bar using the `window_decorations ` option.

I tried this by installing wezterm via their ppa as well as flatpak. I'm on Ubuntu 24.04, Gnome 46, wayland

**Comment by naddeoa** [comment]
Looks like it crashes when I plug in a new monitor too, I assume because the new monitor is bigger and that increases the size of the terminal. For now, I'm working around this by using kitty instead of wezterm in the drop down and only using wezterm stand alone for programming stuff as a normal window.

**Comment by naddeoa** [comment]
Ok, looks like this is actually a wezterm x wayland issue. I didn't notice it when I was using tdrop because I launch tdrop with `WAYLAND_DISPLAY=no`, which was flowing through to wezterm as well.

Is there some way I can customize the launch arguments for the shell? I would need to launch wezterm with that env var to avoid it crashing.

**Comment by diegodario88** [comment]
> Is there some way I can customize the launch arguments for the shell? I would need to launch wezterm with that env var to avoid it crashing.

Not at the moment, but there’s a draft implementation suggested [here](https://github.com/diegodario88/quake-terminal/issues/30).
