### ISSUE TITLE
Exception when opening the extension's settings

### ISSUE THREAD

**Issue by rotorek** [diegodario88/quake-terminal#4]
When enabling the extension and clicking on its Settings, I get:

```
Error: Invalid value 'undefined' for property accelerator in object initializer.

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
  fillPreferencesWindow@file:///home/ondrej/.local/share/gnome-shell/extensions/quake-terminal@diegodario88.github.io/prefs.js:66:25
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:36:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```
(I'm running SuSE Tumbleweed VERSION="20231008")

**Comment by diegodario88** [comment]
Unfortunately, I was unable to reproduce this error 😔. There's a default value in the schema for the `terminal-shortcut` entry, and it shouldn't be undefined. However, I made a small fix to prevent that from happening.

I would also suggest a clean install: remove the extension and delete the dconf entries using the following command:

```shell
 dconf reset -f /org/gnome/shell/extensions/quake-terminal@diegodario88.github.io/
 ```

Then, log out and install from the main branch. I hope this fixes it for you.

**Comment by rotorek** [comment]
Thank you. I works great now!

**Comment by diegodario88** [comment]
I'm glad I could help you. If you find our open-source project valuable, please consider showing your support by donating or leaving a star on our repository. It means a lot to me.
