### ISSUE TITLE
Shortcut to open terminal moves me to workspace where the terminal is located

### ISSUE THREAD

**Issue by Huholoman** [diegodario88/quake-terminal#43]
I really like this extension, but for some reason it stopped showing me terminal on current workspace, when I want to open terminal, it moves me to the workspace, where it is open. 
Steps to reproduce:
* I open gnome-terminal on workspace 1,
* I go to workspace 2 and press shortcut to open my terminal,
* it moves me to workspace 1.

At least a week ago it opened me the gnome-terminal on the current workspace.

**Comment by diegodario88** [comment]
I can't reproduce this behavior 😕

**Comment by Huholoman** [comment]
@diegodario88 Hmm, I just checked again and it works. Maybe there was some issue after last update before I restarted pc :see_no_evil: But it happened to me on my personal and work PC, so I though its not just some accident on one PC.

Sorry for false alarm, I hope it havent consummed much of your time.
