### ISSUE TITLE
Support multi-screen

### ISSUE THREAD

**Issue by Henry78** [diegodario88/quake-terminal#5]
I switched over from quake-mode and miss the possibility to configure the screen where the dropdown appears. 

I got a laptop with an external screen. The external screen is Primary Display, but quake-terminal pops up at the laptop screen, which makes it pretty unusable for me.

**Comment by diegodario88** [comment]
That's a valid point. I should experiment with something in my free time to see what I can come up with. 🫡

**Comment by Henry78** [comment]
That was quick! ❤️

**Comment by diegodario88** [comment]
I'm glad I could help you. If you find our open-source project valuable, please consider showing your support by donating or leaving a star on our repository. It means a lot to me.
